### ISSUE TITLE
updateObjectAttribute fails when the attribute is an object reference

### ISSUE THREAD

**Issue by kralleman** [Riada-AB/InsightManager#18]
If passing an object bean instead of object ID as the attribute value when calling updateObjectAttribute (possibly also updateObjectAttributes), Insight will throw a validation exception like this:

Validation errors were found: rlabs-insight-attribute-41519: ErrorMessage{i18nKey='rlabs.insight.i18n.constraint.violation.ObjectAttributeValueBean.MinOne.value', parameters=[], additionalMessage=null};

**Comment by AndersAtRiada** [comment]
I´ve confirmed the issue and i´m currently in the middle of testing a fix. 

Working in branch: https://github.com/Riada-AB/InsightManager/tree/fixingIssue-%2318

**Comment by ItsAtRiada** [comment]
This should now be fixed and is now part of the SPOC testing run before any merges to the Master branch.
