### ISSUE TITLE
renderObjectToHtml is returning incorrect Label for referenced objects with no Avatar

### ISSUE THREAD

**Issue by martinhaagen** [Riada-AB/InsightManager#23]
renderObjectToHtml is returning ${object.label} instead of ${referencedObject.label} for referenced objects without avatars.

![image](https://user-images.githubusercontent.com/75038803/100264402-13709800-2f4f-11eb-9722-3ea99e266652.png)

**Comment by martinhaagen** [comment]
Also, perhaps change the attribute values to be sorted by label so it looks nicer
Row 1115
`it.value.sort { it.label }.each { referencedObject ->`

**Comment by ItsAtRiada** [comment]
Nice find and fix, thanks!
